// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Office.DataBase;

#nullable disable

namespace Pulse.DataBase.Migrations
{
    [DbContext(typeof(ApplicationContext))]
    [Migration("20250906205348_AddMediaFileTable")]
    partial class AddMediaFileTable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.20")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("DocumentRequest", b =>
                {
                    b.Property<int>("FilesDocumentId")
                        .HasColumnType("integer");

                    b.Property<int>("RequestsRequestId")
                        .HasColumnType("integer");

                    b.HasKey("FilesDocumentId", "RequestsRequestId");

                    b.HasIndex("RequestsRequestId");

                    b.ToTable("DocumentRequest");
                });

            modelBuilder.Entity("Domain.Client", b =>
                {
                    b.Property<int>("ClientId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ClientId"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("Contact")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("date");

                    b.Property<string>("EMail")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<bool>("IsArchive")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.HasKey("ClientId");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Clients");
                });

            modelBuilder.Entity("Domain.Document", b =>
                {
                    b.Property<int>("DocumentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("DocumentId"));

                    b.Property<string>("Extension")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<byte[]>("File")
                        .IsRequired()
                        .HasColumnType("bytea");

                    b.Property<string>("Hash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("DocumentId");

                    b.ToTable("Documents");
                });

            modelBuilder.Entity("Domain.Experience", b =>
                {
                    b.Property<int>("ExperienceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ExperienceId"));

                    b.Property<DateTime>("Date")
                        .HasColumnType("date");

                    b.Property<string>("DoneWork")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("Garant")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsArchive")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsTaskAccepted")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsWorkDone")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsWorkPlaceClean")
                        .HasColumnType("boolean");

                    b.Property<int?>("MainWorkerId")
                        .HasColumnType("integer");

                    b.Property<string>("RemainWork")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("ReportState")
                        .HasColumnType("integer");

                    b.Property<int>("RequestId")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("TimeEnd")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime?>("TimeStart")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("UsedMaterials")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("WorkPlan")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("ExperienceId");

                    b.HasIndex("MainWorkerId");

                    b.HasIndex("RequestId");

                    b.ToTable("Experiences");
                });

            modelBuilder.Entity("Domain.Log", b =>
                {
                    b.Property<int>("LogId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("LogId"));

                    b.Property<int>("AuthorId")
                        .HasColumnType("integer");

                    b.Property<int>("AuthorProffesionType")
                        .HasColumnType("integer");

                    b.Property<int>("LogType")
                        .HasColumnType("integer");

                    b.Property<string>("NewVersion")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("OldVersion")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.HasKey("LogId");

                    b.ToTable("Logs");
                });

            modelBuilder.Entity("Domain.Manager", b =>
                {
                    b.Property<int>("ManagerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ManagerId"));

                    b.Property<string>("ApiKey")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<bool>("IsArchive")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.HasKey("ManagerId");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Managers");
                });

            modelBuilder.Entity("Domain.MediaFile", b =>
                {
                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("MimeType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("ReportId")
                        .HasColumnType("integer");

                    b.HasKey("Name");

                    b.HasIndex("ReportId");

                    b.ToTable("MediaFiles");
                });

            modelBuilder.Entity("Domain.Report", b =>
                {
                    b.Property<int>("ReportId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ReportId"));

                    b.Property<DateTime>("Date")
                        .HasColumnType("date");

                    b.Property<string>("DoneWork")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("EndTime")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("ExperienceId")
                        .HasColumnType("integer");

                    b.Property<bool>("IsArchive")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsWorkAccept")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsWorkDone")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsWorkplaceClean")
                        .HasColumnType("boolean");

                    b.Property<string>("MediaIds")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("RemainWork")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("StartTime")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UpdateOn")
                        .HasColumnType("date");

                    b.Property<string>("UsedMaterials")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("WorkerId")
                        .HasColumnType("integer");

                    b.HasKey("ReportId");

                    b.HasIndex("ExperienceId");

                    b.HasIndex("WorkerId");

                    b.ToTable("Reports");
                });

            modelBuilder.Entity("Domain.Request", b =>
                {
                    b.Property<int>("RequestId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("RequestId"));

                    b.Property<string>("ActFilePath")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("ClientId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("Date")
                        .HasColumnType("date");

                    b.Property<int?>("DocumentId")
                        .HasColumnType("integer");

                    b.Property<string>("InternalInfo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsArchive")
                        .HasColumnType("boolean");

                    b.Property<int>("ManagerId")
                        .HasColumnType("integer");

                    b.Property<string>("NecessaryFunds")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ReasonRequest")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<int>("WorkResultType")
                        .HasColumnType("integer");

                    b.HasKey("RequestId");

                    b.HasIndex("ClientId");

                    b.HasIndex("DocumentId");

                    b.HasIndex("ManagerId");

                    b.ToTable("Requests");
                });

            modelBuilder.Entity("Domain.Worker", b =>
                {
                    b.Property<int>("WorkerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("WorkerId"));

                    b.Property<string>("ApiKey")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("HourSalary")
                        .HasColumnType("integer");

                    b.Property<bool>("IsArchive")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<int>("ShiftSalary")
                        .HasColumnType("integer");

                    b.HasKey("WorkerId");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Workers");
                });

            modelBuilder.Entity("ExperienceWorker", b =>
                {
                    b.Property<int>("ExperienciesExperienceId")
                        .HasColumnType("integer");

                    b.Property<int>("WorkersWorkerId")
                        .HasColumnType("integer");

                    b.HasKey("ExperienciesExperienceId", "WorkersWorkerId");

                    b.HasIndex("WorkersWorkerId");

                    b.ToTable("ExperienceWorker");
                });

            modelBuilder.Entity("DocumentRequest", b =>
                {
                    b.HasOne("Domain.Document", null)
                        .WithMany()
                        .HasForeignKey("FilesDocumentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Request", null)
                        .WithMany()
                        .HasForeignKey("RequestsRequestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Domain.Experience", b =>
                {
                    b.HasOne("Domain.Worker", "MainWorker")
                        .WithMany()
                        .HasForeignKey("MainWorkerId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Domain.Request", "Request")
                        .WithMany("Experiencies")
                        .HasForeignKey("RequestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MainWorker");

                    b.Navigation("Request");
                });

            modelBuilder.Entity("Domain.MediaFile", b =>
                {
                    b.HasOne("Domain.Report", "Report")
                        .WithMany("MediaFiles")
                        .HasForeignKey("ReportId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Report");
                });

            modelBuilder.Entity("Domain.Report", b =>
                {
                    b.HasOne("Domain.Experience", "Experience")
                        .WithMany("Reports")
                        .HasForeignKey("ExperienceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Worker", "Worker")
                        .WithMany("Reports")
                        .HasForeignKey("WorkerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Experience");

                    b.Navigation("Worker");
                });

            modelBuilder.Entity("Domain.Request", b =>
                {
                    b.HasOne("Domain.Client", "Client")
                        .WithMany("Requests")
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Document", "Document")
                        .WithMany()
                        .HasForeignKey("DocumentId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Domain.Manager", "Manager")
                        .WithMany("Requests")
                        .HasForeignKey("ManagerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Client");

                    b.Navigation("Document");

                    b.Navigation("Manager");
                });

            modelBuilder.Entity("ExperienceWorker", b =>
                {
                    b.HasOne("Domain.Experience", null)
                        .WithMany()
                        .HasForeignKey("ExperienciesExperienceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Worker", null)
                        .WithMany()
                        .HasForeignKey("WorkersWorkerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Domain.Client", b =>
                {
                    b.Navigation("Requests");
                });

            modelBuilder.Entity("Domain.Experience", b =>
                {
                    b.Navigation("Reports");
                });

            modelBuilder.Entity("Domain.Manager", b =>
                {
                    b.Navigation("Requests");
                });

            modelBuilder.Entity("Domain.Report", b =>
                {
                    b.Navigation("MediaFiles");
                });

            modelBuilder.Entity("Domain.Request", b =>
                {
                    b.Navigation("Experiencies");
                });

            modelBuilder.Entity("Domain.Worker", b =>
                {
                    b.Navigation("Reports");
                });
#pragma warning restore 612, 618
        }
    }
}
